use ucd::{Script, UnicodeBlock, UnicodeCategory};
use unicode_security::general_security_profile::IdentifierType;

pub fn char_identifier_to_string(ident: IdentifierType) -> &'static str {
    match ident {
        IdentifierType::Not_Character => "Not Character",
        IdentifierType::Deprecated => "Deprecated",
        IdentifierType::Default_Ignorable => "Default Ignorable",
        IdentifierType::Not_NFKC => "Not NFKC",
        IdentifierType::Not_XID => "Not XID",
        IdentifierType::Exclusion => "Exclusion",
        IdentifierType::Obsolete => "Obsolete",
        IdentifierType::Technical => "Technical",
        IdentifierType::Uncommon_Use => "Uncommon Use",
        IdentifierType::Limited_Use => "Limited Use",
        IdentifierType::Inclusion => "Inclusion",
        IdentifierType::Recommended => "Recommended",
    }
}

pub fn general_category_to_string(cat: UnicodeCategory) -> &'static str {
    match cat {
        UnicodeCategory::ClosePunctuation => "ClosePunctuation",
        UnicodeCategory::ConnectorPunctuation => "ConnectorPunctuation",
        UnicodeCategory::Control => "Control",
        UnicodeCategory::CurrencySymbol => "CurrencySymbol",
        UnicodeCategory::DashPunctuation => "DashPunctuation",
        UnicodeCategory::DecimalNumber => "DecimalNumber",
        UnicodeCategory::EnclosingMark => "EnclosingMark",
        UnicodeCategory::FinalPunctuation => "FinalPunctuation",
        UnicodeCategory::Format => "Format",
        UnicodeCategory::InitialPunctuation => "InitialPunctuation",
        UnicodeCategory::LetterNumber => "LetterNumber",
        UnicodeCategory::LineSeparator => "LineSeparator",
        UnicodeCategory::LowercaseLetter => "LowercaseLetter",
        UnicodeCategory::MathSymbol => "MathSymbol",
        UnicodeCategory::ModifierLetter => "ModifierLetter",
        UnicodeCategory::ModifierSymbol => "ModifierSymbol",
        UnicodeCategory::NonspacingMark => "NonspacingMark",
        UnicodeCategory::OpenPunctuation => "OpenPunctuation",
        UnicodeCategory::OtherLetter => "OtherLetter",
        UnicodeCategory::OtherNumber => "OtherNumber",
        UnicodeCategory::OtherPunctuation => "OtherPunctuation",
        UnicodeCategory::OtherSymbol => "OtherSymbol",
        UnicodeCategory::ParagraphSeparator => "ParagraphSeparator",
        UnicodeCategory::PrivateUse => "PrivateUse",
        UnicodeCategory::SpaceSeparator => "SpaceSeparator",
        UnicodeCategory::SpacingMark => "SpacingMark",
        UnicodeCategory::Surrogate => "Surrogate",
        UnicodeCategory::TitlecaseLetter => "TitlecaseLetter",
        UnicodeCategory::Unassigned => "Unassigned",
        UnicodeCategory::UppercaseLetter => "UppercaseLetter",
    }
}

pub fn unicode_block_to_string(block: Option<UnicodeBlock>) -> &'static str {
    match block {
        Some(block) => match block {
            UnicodeBlock::BasicLatin => "BasicLatin",
            UnicodeBlock::Latin1Supplement => "Latin1Supplement",
            UnicodeBlock::LatinExtendedA => "LatinExtendedA",
            UnicodeBlock::LatinExtendedB => "LatinExtendedB",
            UnicodeBlock::IPAExtensions => "IPAExtensions",
            UnicodeBlock::SpacingModifierLetters => "SpacingModifierLetters",
            UnicodeBlock::CombiningDiacriticalMarks => "CombiningDiacriticalMarks",
            UnicodeBlock::GreekandCoptic => "GreekandCoptic",
            UnicodeBlock::Cyrillic => "Cyrillic",
            UnicodeBlock::CyrillicSupplement => "CyrillicSupplement",
            UnicodeBlock::Armenian => "Armenian",
            UnicodeBlock::Hebrew => "Hebrew",
            UnicodeBlock::Arabic => "Arabic",
            UnicodeBlock::Syriac => "Syriac",
            UnicodeBlock::ArabicSupplement => "ArabicSupplement",
            UnicodeBlock::Thaana => "Thaana",
            UnicodeBlock::NKo => "NKo",
            UnicodeBlock::Samaritan => "Samaritan",
            UnicodeBlock::Mandaic => "Mandaic",
            UnicodeBlock::ArabicExtendedA => "ArabicExtendedA",
            UnicodeBlock::Devanagari => "Devanagari",
            UnicodeBlock::Bengali => "Bengali",
            UnicodeBlock::Gurmukhi => "Gurmukhi",
            UnicodeBlock::Gujarati => "Gujarati",
            UnicodeBlock::Oriya => "Oriya",
            UnicodeBlock::Tamil => "Tamil",
            UnicodeBlock::Telugu => "Telugu",
            UnicodeBlock::Kannada => "Kannada",
            UnicodeBlock::Malayalam => "Malayalam",
            UnicodeBlock::Sinhala => "Sinhala",
            UnicodeBlock::Thai => "Thai",
            UnicodeBlock::Lao => "Lao",
            UnicodeBlock::Tibetan => "Tibetan",
            UnicodeBlock::Myanmar => "Myanmar",
            UnicodeBlock::Georgian => "Georgian",
            UnicodeBlock::HangulJamo => "HangulJamo",
            UnicodeBlock::Ethiopic => "Ethiopic",
            UnicodeBlock::EthiopicSupplement => "EthiopicSupplement",
            UnicodeBlock::Cherokee => "Cherokee",
            UnicodeBlock::UnifiedCanadianAboriginalSyllabics => {
                "UnifiedCanadianAboriginalSyllabics"
            }
            UnicodeBlock::Ogham => "Ogham",
            UnicodeBlock::Runic => "Runic",
            UnicodeBlock::Tagalog => "Tagalog",
            UnicodeBlock::Hanunoo => "Hanunoo",
            UnicodeBlock::Buhid => "Buhid",
            UnicodeBlock::Tagbanwa => "Tagbanwa",
            UnicodeBlock::Khmer => "Khmer",
            UnicodeBlock::Mongolian => "Mongolian",
            UnicodeBlock::UnifiedCanadianAboriginalSyllabicsExtended => {
                "UnifiedCanadianAboriginalSyllabicsExtended"
            }
            UnicodeBlock::Limbu => "Limbu",
            UnicodeBlock::TaiLe => "TaiLe",
            UnicodeBlock::NewTaiLue => "NewTaiLue",
            UnicodeBlock::KhmerSymbols => "KhmerSymbols",
            UnicodeBlock::Buginese => "Buginese",
            UnicodeBlock::TaiTham => "TaiTham",
            UnicodeBlock::CombiningDiacriticalMarksExtended => {
                "CombiningDiacriticalMarksExtended"
            }
            UnicodeBlock::Balinese => "Balinese",
            UnicodeBlock::Sundanese => "Sundanese",
            UnicodeBlock::Batak => "Batak",
            UnicodeBlock::Lepcha => "Lepcha",
            UnicodeBlock::OlChiki => "OlChiki",
            UnicodeBlock::CyrillicExtendedC => "CyrillicExtendedC",
            UnicodeBlock::SundaneseSupplement => "SundaneseSupplement",
            UnicodeBlock::VedicExtensions => "VedicExtensions",
            UnicodeBlock::PhoneticExtensions => "PhoneticExtensions",
            UnicodeBlock::PhoneticExtensionsSupplement => "PhoneticExtensionsSupplement",
            UnicodeBlock::CombiningDiacriticalMarksSupplement => {
                "CombiningDiacriticalMarksSupplement"
            }
            UnicodeBlock::LatinExtendedAdditional => "LatinExtendedAdditional",
            UnicodeBlock::GreekExtended => "GreekExtended",
            UnicodeBlock::GeneralPunctuation => "GeneralPunctuation",
            UnicodeBlock::SuperscriptsandSubscripts => "SuperscriptsandSubscripts",
            UnicodeBlock::CurrencySymbols => "CurrencySymbols",
            UnicodeBlock::CombiningDiacriticalMarksforSymbols => {
                "CombiningDiacriticalMarksforSymbols"
            }
            UnicodeBlock::LetterlikeSymbols => "LetterlikeSymbols",
            UnicodeBlock::NumberForms => "NumberForms",
            UnicodeBlock::Arrows => "Arrows",
            UnicodeBlock::MathematicalOperators => "MathematicalOperators",
            UnicodeBlock::MiscellaneousTechnical => "MiscellaneousTechnical",
            UnicodeBlock::ControlPictures => "ControlPictures",
            UnicodeBlock::OpticalCharacterRecognition => "OpticalCharacterRecognition",
            UnicodeBlock::EnclosedAlphanumerics => "EnclosedAlphanumerics",
            UnicodeBlock::BoxDrawing => "BoxDrawing",
            UnicodeBlock::BlockElements => "BlockElements",
            UnicodeBlock::GeometricShapes => "GeometricShapes",
            UnicodeBlock::MiscellaneousSymbols => "MiscellaneousSymbols",
            UnicodeBlock::Dingbats => "Dingbats",
            UnicodeBlock::MiscellaneousMathematicalSymbolsA => {
                "MiscellaneousMathematicalSymbolsA"
            }
            UnicodeBlock::SupplementalArrowsA => "SupplementalArrowsA",
            UnicodeBlock::BraillePatterns => "BraillePatterns",
            UnicodeBlock::SupplementalArrowsB => "SupplementalArrowsB",
            UnicodeBlock::MiscellaneousMathematicalSymbolsB => {
                "MiscellaneousMathematicalSymbolsB"
            }
            UnicodeBlock::SupplementalMathematicalOperators => {
                "SupplementalMathematicalOperators"
            }
            UnicodeBlock::MiscellaneousSymbolsandArrows => "MiscellaneousSymbolsandArrows",
            UnicodeBlock::Glagolitic => "Glagolitic",
            UnicodeBlock::LatinExtendedC => "LatinExtendedC",
            UnicodeBlock::Coptic => "Coptic",
            UnicodeBlock::GeorgianSupplement => "GeorgianSupplement",
            UnicodeBlock::Tifinagh => "Tifinagh",
            UnicodeBlock::EthiopicExtended => "EthiopicExtended",
            UnicodeBlock::CyrillicExtendedA => "CyrillicExtendedA",
            UnicodeBlock::SupplementalPunctuation => "SupplementalPunctuation",
            UnicodeBlock::CJKRadicalsSupplement => "CJKRadicalsSupplement",
            UnicodeBlock::KangxiRadicals => "KangxiRadicals",
            UnicodeBlock::IdeographicDescriptionCharacters => {
                "IdeographicDescriptionCharacters"
            }
            UnicodeBlock::CJKSymbolsandPunctuation => "CJKSymbolsandPunctuation",
            UnicodeBlock::Hiragana => "Hiragana",
            UnicodeBlock::Katakana => "Katakana",
            UnicodeBlock::Bopomofo => "Bopomofo",
            UnicodeBlock::HangulCompatibilityJamo => "HangulCompatibilityJamo",
            UnicodeBlock::Kanbun => "Kanbun",
            UnicodeBlock::BopomofoExtended => "BopomofoExtended",
            UnicodeBlock::CJKStrokes => "CJKStrokes",
            UnicodeBlock::KatakanaPhoneticExtensions => "KatakanaPhoneticExtensions",
            UnicodeBlock::EnclosedCJKLettersandMonths => "EnclosedCJKLettersandMonths",
            UnicodeBlock::CJKCompatibility => "CJKCompatibility",
            UnicodeBlock::CJKUnifiedIdeographsExtensionA => "CJKUnifiedIdeographsExtensionA",
            UnicodeBlock::YijingHexagramSymbols => "YijingHexagramSymbols",
            UnicodeBlock::CJKUnifiedIdeographs => "CJKUnifiedIdeographs",
            UnicodeBlock::YiSyllables => "YiSyllables",
            UnicodeBlock::YiRadicals => "YiRadicals",
            UnicodeBlock::Lisu => "Lisu",
            UnicodeBlock::Vai => "Vai",
            UnicodeBlock::CyrillicExtendedB => "CyrillicExtendedB",
            UnicodeBlock::Bamum => "Bamum",
            UnicodeBlock::ModifierToneLetters => "ModifierToneLetters",
            UnicodeBlock::LatinExtendedD => "LatinExtendedD",
            UnicodeBlock::SylotiNagri => "SylotiNagri",
            UnicodeBlock::CommonIndicNumberForms => "CommonIndicNumberForms",
            UnicodeBlock::Phagspa => "Phagspa",
            UnicodeBlock::Saurashtra => "Saurashtra",
            UnicodeBlock::DevanagariExtended => "DevanagariExtended",
            UnicodeBlock::KayahLi => "KayahLi",
            UnicodeBlock::Rejang => "Rejang",
            UnicodeBlock::HangulJamoExtendedA => "HangulJamoExtendedA",
            UnicodeBlock::Javanese => "Javanese",
            UnicodeBlock::MyanmarExtendedB => "MyanmarExtendedB",
            UnicodeBlock::Cham => "Cham",
            UnicodeBlock::MyanmarExtendedA => "MyanmarExtendedA",
            UnicodeBlock::TaiViet => "TaiViet",
            UnicodeBlock::MeeteiMayekExtensions => "MeeteiMayekExtensions",
            UnicodeBlock::EthiopicExtendedA => "EthiopicExtendedA",
            UnicodeBlock::LatinExtendedE => "LatinExtendedE",
            UnicodeBlock::CherokeeSupplement => "CherokeeSupplement",
            UnicodeBlock::MeeteiMayek => "MeeteiMayek",
            UnicodeBlock::HangulSyllables => "HangulSyllables",
            UnicodeBlock::HangulJamoExtendedB => "HangulJamoExtendedB",
            UnicodeBlock::HighSurrogates => "HighSurrogates",
            UnicodeBlock::HighPrivateUseSurrogates => "HighPrivateUseSurrogates",
            UnicodeBlock::LowSurrogates => "LowSurrogates",
            UnicodeBlock::PrivateUseArea => "PrivateUseArea",
            UnicodeBlock::CJKCompatibilityIdeographs => "CJKCompatibilityIdeographs",
            UnicodeBlock::AlphabeticPresentationForms => "AlphabeticPresentationForms",
            UnicodeBlock::ArabicPresentationFormsA => "ArabicPresentationFormsA",
            UnicodeBlock::VariationSelectors => "VariationSelectors",
            UnicodeBlock::VerticalForms => "VerticalForms",
            UnicodeBlock::CombiningHalfMarks => "CombiningHalfMarks",
            UnicodeBlock::CJKCompatibilityForms => "CJKCompatibilityForms",
            UnicodeBlock::SmallFormVariants => "SmallFormVariants",
            UnicodeBlock::ArabicPresentationFormsB => "ArabicPresentationFormsB",
            UnicodeBlock::HalfwidthandFullwidthForms => "HalfwidthandFullwidthForms",
            UnicodeBlock::Specials => "Specials",
            UnicodeBlock::LinearBSyllabary => "LinearBSyllabary",
            UnicodeBlock::LinearBIdeograms => "LinearBIdeograms",
            UnicodeBlock::AegeanNumbers => "AegeanNumbers",
            UnicodeBlock::AncientGreekNumbers => "AncientGreekNumbers",
            UnicodeBlock::AncientSymbols => "AncientSymbols",
            UnicodeBlock::PhaistosDisc => "PhaistosDisc",
            UnicodeBlock::Lycian => "Lycian",
            UnicodeBlock::Carian => "Carian",
            UnicodeBlock::CopticEpactNumbers => "CopticEpactNumbers",
            UnicodeBlock::OldItalic => "OldItalic",
            UnicodeBlock::Gothic => "Gothic",
            UnicodeBlock::OldPermic => "OldPermic",
            UnicodeBlock::Ugaritic => "Ugaritic",
            UnicodeBlock::OldPersian => "OldPersian",
            UnicodeBlock::Deseret => "Deseret",
            UnicodeBlock::Shavian => "Shavian",
            UnicodeBlock::Osmanya => "Osmanya",
            UnicodeBlock::Osage => "Osage",
            UnicodeBlock::Elbasan => "Elbasan",
            UnicodeBlock::CaucasianAlbanian => "CaucasianAlbanian",
            UnicodeBlock::LinearA => "LinearA",
            UnicodeBlock::CypriotSyllabary => "CypriotSyllabary",
            UnicodeBlock::ImperialAramaic => "ImperialAramaic",
            UnicodeBlock::Palmyrene => "Palmyrene",
            UnicodeBlock::Nabataean => "Nabataean",
            UnicodeBlock::Hatran => "Hatran",
            UnicodeBlock::Phoenician => "Phoenician",
            UnicodeBlock::Lydian => "Lydian",
            UnicodeBlock::MeroiticHieroglyphs => "MeroiticHieroglyphs",
            UnicodeBlock::MeroiticCursive => "MeroiticCursive",
            UnicodeBlock::Kharoshthi => "Kharoshthi",
            UnicodeBlock::OldSouthArabian => "OldSouthArabian",
            UnicodeBlock::OldNorthArabian => "OldNorthArabian",
            UnicodeBlock::Manichaean => "Manichaean",
            UnicodeBlock::Avestan => "Avestan",
            UnicodeBlock::InscriptionalParthian => "InscriptionalParthian",
            UnicodeBlock::InscriptionalPahlavi => "InscriptionalPahlavi",
            UnicodeBlock::PsalterPahlavi => "PsalterPahlavi",
            UnicodeBlock::OldTurkic => "OldTurkic",
            UnicodeBlock::OldHungarian => "OldHungarian",
            UnicodeBlock::RumiNumeralSymbols => "RumiNumeralSymbols",
            UnicodeBlock::Brahmi => "Brahmi",
            UnicodeBlock::Kaithi => "Kaithi",
            UnicodeBlock::SoraSompeng => "SoraSompeng",
            UnicodeBlock::Chakma => "Chakma",
            UnicodeBlock::Mahajani => "Mahajani",
            UnicodeBlock::Sharada => "Sharada",
            UnicodeBlock::SinhalaArchaicNumbers => "SinhalaArchaicNumbers",
            UnicodeBlock::Khojki => "Khojki",
            UnicodeBlock::Multani => "Multani",
            UnicodeBlock::Khudawadi => "Khudawadi",
            UnicodeBlock::Grantha => "Grantha",
            UnicodeBlock::Newa => "Newa",
            UnicodeBlock::Tirhuta => "Tirhuta",
            UnicodeBlock::Siddham => "Siddham",
            UnicodeBlock::Modi => "Modi",
            UnicodeBlock::MongolianSupplement => "MongolianSupplement",
            UnicodeBlock::Takri => "Takri",
            UnicodeBlock::Ahom => "Ahom",
            UnicodeBlock::WarangCiti => "WarangCiti",
            UnicodeBlock::PauCinHau => "PauCinHau",
            UnicodeBlock::Bhaiksuki => "Bhaiksuki",
            UnicodeBlock::Marchen => "Marchen",
            UnicodeBlock::Cuneiform => "Cuneiform",
            UnicodeBlock::CuneiformNumbersandPunctuation => "CuneiformNumbersandPunctuation",
            UnicodeBlock::EarlyDynasticCuneiform => "EarlyDynasticCuneiform",
            UnicodeBlock::EgyptianHieroglyphs => "EgyptianHieroglyphs",
            UnicodeBlock::AnatolianHieroglyphs => "AnatolianHieroglyphs",
            UnicodeBlock::BamumSupplement => "BamumSupplement",
            UnicodeBlock::Mro => "Mro",
            UnicodeBlock::BassaVah => "BassaVah",
            UnicodeBlock::PahawhHmong => "PahawhHmong",
            UnicodeBlock::Miao => "Miao",
            UnicodeBlock::IdeographicSymbolsandPunctuation => {
                "IdeographicSymbolsandPunctuation"
            }
            UnicodeBlock::Tangut => "Tangut",
            UnicodeBlock::TangutComponents => "TangutComponents",
            UnicodeBlock::KanaSupplement => "KanaSupplement",
            UnicodeBlock::Duployan => "Duployan",
            UnicodeBlock::ShorthandFormatControls => "ShorthandFormatControls",
            UnicodeBlock::ByzantineMusicalSymbols => "ByzantineMusicalSymbols",
            UnicodeBlock::MusicalSymbols => "MusicalSymbols",
            UnicodeBlock::AncientGreekMusicalNotation => "AncientGreekMusicalNotation",
            UnicodeBlock::TaiXuanJingSymbols => "TaiXuanJingSymbols",
            UnicodeBlock::CountingRodNumerals => "CountingRodNumerals",
            UnicodeBlock::MathematicalAlphanumericSymbols => {
                "MathematicalAlphanumericSymbols"
            }
            UnicodeBlock::SuttonSignWriting => "SuttonSignWriting",
            UnicodeBlock::GlagoliticSupplement => "GlagoliticSupplement",
            UnicodeBlock::MendeKikakui => "MendeKikakui",
            UnicodeBlock::Adlam => "Adlam",
            UnicodeBlock::ArabicMathematicalAlphabeticSymbols => {
                "ArabicMathematicalAlphabeticSymbols"
            }
            UnicodeBlock::MahjongTiles => "MahjongTiles",
            UnicodeBlock::DominoTiles => "DominoTiles",
            UnicodeBlock::PlayingCards => "PlayingCards",
            UnicodeBlock::EnclosedAlphanumericSupplement => "EnclosedAlphanumericSupplement",
            UnicodeBlock::EnclosedIdeographicSupplement => "EnclosedIdeographicSupplement",
            UnicodeBlock::MiscellaneousSymbolsandPictographs => {
                "MiscellaneousSymbolsandPictographs"
            }
            UnicodeBlock::Emoticons => "Emoticons",
            UnicodeBlock::OrnamentalDingbats => "OrnamentalDingbats",
            UnicodeBlock::TransportandMapSymbols => "TransportandMapSymbols",
            UnicodeBlock::AlchemicalSymbols => "AlchemicalSymbols",
            UnicodeBlock::GeometricShapesExtended => "GeometricShapesExtended",
            UnicodeBlock::SupplementalArrowsC => "SupplementalArrowsC",
            UnicodeBlock::SupplementalSymbolsandPictographs => {
                "SupplementalSymbolsandPictographs"
            }
            UnicodeBlock::CJKUnifiedIdeographsExtensionB => "CJKUnifiedIdeographsExtensionB",
            UnicodeBlock::CJKUnifiedIdeographsExtensionC => "CJKUnifiedIdeographsExtensionC",
            UnicodeBlock::CJKUnifiedIdeographsExtensionD => "CJKUnifiedIdeographsExtensionD",
            UnicodeBlock::CJKUnifiedIdeographsExtensionE => "CJKUnifiedIdeographsExtensionE",
            UnicodeBlock::CJKCompatibilityIdeographsSupplement => {
                "CJKCompatibilityIdeographsSupplement"
            }
            UnicodeBlock::Tags => "Tags",
            UnicodeBlock::VariationSelectorsSupplement => "VariationSelectorsSupplement",
            UnicodeBlock::SupplementaryPrivateUseAreaA => "SupplementaryPrivateUseAreaA",
            UnicodeBlock::SupplementaryPrivateUseAreaB => "SupplementaryPrivateUseAreaB",
        },
        None => "Unknown Unicode Block",
    }
}

pub fn unicode_script_to_string(script: Option<Script>) -> &'static str {
    match script {
        Some(script) => match script {
            Script::Adlam => "Adlam",
            Script::CaucasianAlbanian => "CaucasianAlbanian",
            Script::Ahom => "Ahom",
            Script::Arabic => "Arabic",
            Script::ImperialAramaic => "ImperialAramaic",
            Script::Armenian => "Armenian",
            Script::Avestan => "Avestan",
            Script::Balinese => "Balinese",
            Script::Bamum => "Bamum",
            Script::BassaVah => "BassaVah",
            Script::Batak => "Batak",
            Script::Bengali => "Bengali",
            Script::Bhaiksuki => "Bhaiksuki",
            Script::Bopomofo => "Bopomofo",
            Script::Brahmi => "Brahmi",
            Script::Braille => "Braille",
            Script::Buginese => "Buginese",
            Script::Buhid => "Buhid",
            Script::Chakma => "Chakma",
            Script::CanadianAboriginal => "CanadianAboriginal",
            Script::Carian => "Carian",
            Script::Cham => "Cham",
            Script::Cherokee => "Cherokee",
            Script::Coptic => "Coptic",
            Script::Cypriot => "Cypriot",
            Script::Cyrillic => "Cyrillic",
            Script::Devanagari => "Devanagari",
            Script::Deseret => "Deseret",
            Script::Duployan => "Duployan",
            Script::EgyptianHieroglyphs => "EgyptianHieroglyphs",
            Script::Elbasan => "Elbasan",
            Script::Ethiopic => "Ethiopic",
            Script::Georgian => "Georgian",
            Script::Glagolitic => "Glagolitic",
            Script::Gothic => "Gothic",
            Script::Grantha => "Grantha",
            Script::Greek => "Greek",
            Script::Gujarati => "Gujarati",
            Script::Gurmukhi => "Gurmukhi",
            Script::Hangul => "Hangul",
            Script::Han => "Han",
            Script::Hanunoo => "Hanunoo",
            Script::Hatran => "Hatran",
            Script::Hebrew => "Hebrew",
            Script::Hiragana => "Hiragana",
            Script::AnatolianHieroglyphs => "AnatolianHieroglyphs",
            Script::PahawhHmong => "PahawhHmong",
            Script::KatakanaOrHiragana => "KatakanaOrHiragana",
            Script::OldHungarian => "OldHungarian",
            Script::OldItalic => "OldItalic",
            Script::Javanese => "Javanese",
            Script::KayahLi => "KayahLi",
            Script::Katakana => "Katakana",
            Script::Kharoshthi => "Kharoshthi",
            Script::Khmer => "Khmer",
            Script::Khojki => "Khojki",
            Script::Kannada => "Kannada",
            Script::Kaithi => "Kaithi",
            Script::TaiTham => "TaiTham",
            Script::Lao => "Lao",
            Script::Latin => "Latin",
            Script::Lepcha => "Lepcha",
            Script::Limbu => "Limbu",
            Script::LinearA => "LinearA",
            Script::LinearB => "LinearB",
            Script::Lisu => "Lisu",
            Script::Lycian => "Lycian",
            Script::Lydian => "Lydian",
            Script::Mahajani => "Mahajani",
            Script::Mandaic => "Mandaic",
            Script::Manichaean => "Manichaean",
            Script::Marchen => "Marchen",
            Script::MendeKikakui => "MendeKikakui",
            Script::MeroiticCursive => "MeroiticCursive",
            Script::MeroiticHieroglyphs => "MeroiticHieroglyphs",
            Script::Malayalam => "Malayalam",
            Script::Modi => "Modi",
            Script::Mongolian => "Mongolian",
            Script::Mro => "Mro",
            Script::MeeteiMayek => "MeeteiMayek",
            Script::Multani => "Multani",
            Script::Myanmar => "Myanmar",
            Script::OldNorthArabian => "OldNorthArabian",
            Script::Nabataean => "Nabataean",
            Script::Newa => "Newa",
            Script::Nko => "Nko",
            Script::Ogham => "Ogham",
            Script::OlChiki => "OlChiki",
            Script::OldTurkic => "OldTurkic",
            Script::Oriya => "Oriya",
            Script::Osage => "Osage",
            Script::Osmanya => "Osmanya",
            Script::Palmyrene => "Palmyrene",
            Script::PauCinHau => "PauCinHau",
            Script::OldPermic => "OldPermic",
            Script::PhagsPa => "PhagsPa",
            Script::InscriptionalPahlavi => "InscriptionalPahlavi",
            Script::PsalterPahlavi => "PsalterPahlavi",
            Script::Phoenician => "Phoenician",
            Script::Miao => "Miao",
            Script::InscriptionalParthian => "InscriptionalParthian",
            Script::Rejang => "Rejang",
            Script::Runic => "Runic",
            Script::Samaritan => "Samaritan",
            Script::OldSouthArabian => "OldSouthArabian",
            Script::Saurashtra => "Saurashtra",
            Script::SignWriting => "SignWriting",
            Script::Shavian => "Shavian",
            Script::Sharada => "Sharada",
            Script::Siddham => "Siddham",
            Script::Khudawadi => "Khudawadi",
            Script::Sinhala => "Sinhala",
            Script::SoraSompeng => "SoraSompeng",
            Script::Sundanese => "Sundanese",
            Script::SylotiNagri => "SylotiNagri",
            Script::Syriac => "Syriac",
            Script::Tagbanwa => "Tagbanwa",
            Script::Takri => "Takri",
            Script::TaiLe => "TaiLe",
            Script::NewTaiLue => "NewTaiLue",
            Script::Tamil => "Tamil",
            Script::Tangut => "Tangut",
            Script::TaiViet => "TaiViet",
            Script::Telugu => "Telugu",
            Script::Tifinagh => "Tifinagh",
            Script::Tagalog => "Tagalog",
            Script::Thaana => "Thaana",
            Script::Thai => "Thai",
            Script::Tibetan => "Tibetan",
            Script::Tirhuta => "Tirhuta",
            Script::Ugaritic => "Ugaritic",
            Script::Vai => "Vai",
            Script::WarangCiti => "WarangCiti",
            Script::OldPersian => "OldPersian",
            Script::Cuneiform => "Cuneiform",
            Script::Yi => "Yi",
            Script::Inherited => "Inherited",
            Script::Common => "Common",
        },
        None => "Unknown Unicode Script",
    }
}
