use ucd::UnicodeBlock;

pub fn unicode_block_to_string(block: Option<UnicodeBlock>) -> String {
    match block {
        Some(block) => match block {
            UnicodeBlock::BasicLatin => "BasicLatin".into(),
            UnicodeBlock::Latin1Supplement => "Latin1Supplement".into(),
            UnicodeBlock::LatinExtendedA => "LatinExtendedA".into(),
            UnicodeBlock::LatinExtendedB => "LatinExtendedB".into(),
            UnicodeBlock::IPAExtensions => "IPAExtensions".into(),
            UnicodeBlock::SpacingModifierLetters => "SpacingModifierLetters".into(),
            UnicodeBlock::CombiningDiacriticalMarks => "CombiningDiacriticalMarks".into(),
            UnicodeBlock::GreekandCoptic => "GreekandCoptic".into(),
            UnicodeBlock::Cyrillic => "Cyrillic".into(),
            UnicodeBlock::CyrillicSupplement => "CyrillicSupplement".into(),
            UnicodeBlock::Armenian => "Armenian".into(),
            UnicodeBlock::Hebrew => "Hebrew".into(),
            UnicodeBlock::Arabic => "Arabic".into(),
            UnicodeBlock::Syriac => "Syriac".into(),
            UnicodeBlock::ArabicSupplement => "ArabicSupplement".into(),
            UnicodeBlock::Thaana => "Thaana".into(),
            UnicodeBlock::NKo => "NKo".into(),
            UnicodeBlock::Samaritan => "Samaritan".into(),
            UnicodeBlock::Mandaic => "Mandaic".into(),
            UnicodeBlock::ArabicExtendedA => "ArabicExtendedA".into(),
            UnicodeBlock::Devanagari => "Devanagari".into(),
            UnicodeBlock::Bengali => "Bengali".into(),
            UnicodeBlock::Gurmukhi => "Gurmukhi".into(),
            UnicodeBlock::Gujarati => "Gujarati".into(),
            UnicodeBlock::Oriya => "Oriya".into(),
            UnicodeBlock::Tamil => "Tamil".into(),
            UnicodeBlock::Telugu => "Telugu".into(),
            UnicodeBlock::Kannada => "Kannada".into(),
            UnicodeBlock::Malayalam => "Malayalam".into(),
            UnicodeBlock::Sinhala => "Sinhala".into(),
            UnicodeBlock::Thai => "Thai".into(),
            UnicodeBlock::Lao => "Lao".into(),
            UnicodeBlock::Tibetan => "Tibetan".into(),
            UnicodeBlock::Myanmar => "Myanmar".into(),
            UnicodeBlock::Georgian => "Georgian".into(),
            UnicodeBlock::HangulJamo => "HangulJamo".into(),
            UnicodeBlock::Ethiopic => "Ethiopic".into(),
            UnicodeBlock::EthiopicSupplement => "EthiopicSupplement".into(),
            UnicodeBlock::Cherokee => "Cherokee".into(),
            UnicodeBlock::UnifiedCanadianAboriginalSyllabics => {
                "UnifiedCanadianAboriginalSyllabics".into()
            }
            UnicodeBlock::Ogham => "Ogham".into(),
            UnicodeBlock::Runic => "Runic".into(),
            UnicodeBlock::Tagalog => "Tagalog".into(),
            UnicodeBlock::Hanunoo => "Hanunoo".into(),
            UnicodeBlock::Buhid => "Buhid".into(),
            UnicodeBlock::Tagbanwa => "Tagbanwa".into(),
            UnicodeBlock::Khmer => "Khmer".into(),
            UnicodeBlock::Mongolian => "Mongolian".into(),
            UnicodeBlock::UnifiedCanadianAboriginalSyllabicsExtended => {
                "UnifiedCanadianAboriginalSyllabicsExtended".into()
            }
            UnicodeBlock::Limbu => "Limbu".into(),
            UnicodeBlock::TaiLe => "TaiLe".into(),
            UnicodeBlock::NewTaiLue => "NewTaiLue".into(),
            UnicodeBlock::KhmerSymbols => "KhmerSymbols".into(),
            UnicodeBlock::Buginese => "Buginese".into(),
            UnicodeBlock::TaiTham => "TaiTham".into(),
            UnicodeBlock::CombiningDiacriticalMarksExtended => {
                "CombiningDiacriticalMarksExtended".into()
            }
            UnicodeBlock::Balinese => "Balinese".into(),
            UnicodeBlock::Sundanese => "Sundanese".into(),
            UnicodeBlock::Batak => "Batak".into(),
            UnicodeBlock::Lepcha => "Lepcha".into(),
            UnicodeBlock::OlChiki => "OlChiki".into(),
            UnicodeBlock::CyrillicExtendedC => "CyrillicExtendedC".into(),
            UnicodeBlock::SundaneseSupplement => "SundaneseSupplement".into(),
            UnicodeBlock::VedicExtensions => "VedicExtensions".into(),
            UnicodeBlock::PhoneticExtensions => "PhoneticExtensions".into(),
            UnicodeBlock::PhoneticExtensionsSupplement => "PhoneticExtensionsSupplement".into(),
            UnicodeBlock::CombiningDiacriticalMarksSupplement => {
                "CombiningDiacriticalMarksSupplement".into()
            }
            UnicodeBlock::LatinExtendedAdditional => "LatinExtendedAdditional".into(),
            UnicodeBlock::GreekExtended => "GreekExtended".into(),
            UnicodeBlock::GeneralPunctuation => "GeneralPunctuation".into(),
            UnicodeBlock::SuperscriptsandSubscripts => "SuperscriptsandSubscripts".into(),
            UnicodeBlock::CurrencySymbols => "CurrencySymbols".into(),
            UnicodeBlock::CombiningDiacriticalMarksforSymbols => {
                "CombiningDiacriticalMarksforSymbols".into()
            }
            UnicodeBlock::LetterlikeSymbols => "LetterlikeSymbols".into(),
            UnicodeBlock::NumberForms => "NumberForms".into(),
            UnicodeBlock::Arrows => "Arrows".into(),
            UnicodeBlock::MathematicalOperators => "MathematicalOperators".into(),
            UnicodeBlock::MiscellaneousTechnical => "MiscellaneousTechnical".into(),
            UnicodeBlock::ControlPictures => "ControlPictures".into(),
            UnicodeBlock::OpticalCharacterRecognition => "OpticalCharacterRecognition".into(),
            UnicodeBlock::EnclosedAlphanumerics => "EnclosedAlphanumerics".into(),
            UnicodeBlock::BoxDrawing => "BoxDrawing".into(),
            UnicodeBlock::BlockElements => "BlockElements".into(),
            UnicodeBlock::GeometricShapes => "GeometricShapes".into(),
            UnicodeBlock::MiscellaneousSymbols => "MiscellaneousSymbols".into(),
            UnicodeBlock::Dingbats => "Dingbats".into(),
            UnicodeBlock::MiscellaneousMathematicalSymbolsA => {
                "MiscellaneousMathematicalSymbolsA".into()
            }
            UnicodeBlock::SupplementalArrowsA => "SupplementalArrowsA".into(),
            UnicodeBlock::BraillePatterns => "BraillePatterns".into(),
            UnicodeBlock::SupplementalArrowsB => "SupplementalArrowsB".into(),
            UnicodeBlock::MiscellaneousMathematicalSymbolsB => {
                "MiscellaneousMathematicalSymbolsB".into()
            }
            UnicodeBlock::SupplementalMathematicalOperators => {
                "SupplementalMathematicalOperators".into()
            }
            UnicodeBlock::MiscellaneousSymbolsandArrows => "MiscellaneousSymbolsandArrows".into(),
            UnicodeBlock::Glagolitic => "Glagolitic".into(),
            UnicodeBlock::LatinExtendedC => "LatinExtendedC".into(),
            UnicodeBlock::Coptic => "Coptic".into(),
            UnicodeBlock::GeorgianSupplement => "GeorgianSupplement".into(),
            UnicodeBlock::Tifinagh => "Tifinagh".into(),
            UnicodeBlock::EthiopicExtended => "EthiopicExtended".into(),
            UnicodeBlock::CyrillicExtendedA => "CyrillicExtendedA".into(),
            UnicodeBlock::SupplementalPunctuation => "SupplementalPunctuation".into(),
            UnicodeBlock::CJKRadicalsSupplement => "CJKRadicalsSupplement".into(),
            UnicodeBlock::KangxiRadicals => "KangxiRadicals".into(),
            UnicodeBlock::IdeographicDescriptionCharacters => {
                "IdeographicDescriptionCharacters".into()
            }
            UnicodeBlock::CJKSymbolsandPunctuation => "CJKSymbolsandPunctuation".into(),
            UnicodeBlock::Hiragana => "Hiragana".into(),
            UnicodeBlock::Katakana => "Katakana".into(),
            UnicodeBlock::Bopomofo => "Bopomofo".into(),
            UnicodeBlock::HangulCompatibilityJamo => "HangulCompatibilityJamo".into(),
            UnicodeBlock::Kanbun => "Kanbun".into(),
            UnicodeBlock::BopomofoExtended => "BopomofoExtended".into(),
            UnicodeBlock::CJKStrokes => "CJKStrokes".into(),
            UnicodeBlock::KatakanaPhoneticExtensions => "KatakanaPhoneticExtensions".into(),
            UnicodeBlock::EnclosedCJKLettersandMonths => "EnclosedCJKLettersandMonths".into(),
            UnicodeBlock::CJKCompatibility => "CJKCompatibility".into(),
            UnicodeBlock::CJKUnifiedIdeographsExtensionA => "CJKUnifiedIdeographsExtensionA".into(),
            UnicodeBlock::YijingHexagramSymbols => "YijingHexagramSymbols".into(),
            UnicodeBlock::CJKUnifiedIdeographs => "CJKUnifiedIdeographs".into(),
            UnicodeBlock::YiSyllables => "YiSyllables".into(),
            UnicodeBlock::YiRadicals => "YiRadicals".into(),
            UnicodeBlock::Lisu => "Lisu".into(),
            UnicodeBlock::Vai => "Vai".into(),
            UnicodeBlock::CyrillicExtendedB => "CyrillicExtendedB".into(),
            UnicodeBlock::Bamum => "Bamum".into(),
            UnicodeBlock::ModifierToneLetters => "ModifierToneLetters".into(),
            UnicodeBlock::LatinExtendedD => "LatinExtendedD".into(),
            UnicodeBlock::SylotiNagri => "SylotiNagri".into(),
            UnicodeBlock::CommonIndicNumberForms => "CommonIndicNumberForms".into(),
            UnicodeBlock::Phagspa => "Phagspa".into(),
            UnicodeBlock::Saurashtra => "Saurashtra".into(),
            UnicodeBlock::DevanagariExtended => "DevanagariExtended".into(),
            UnicodeBlock::KayahLi => "KayahLi".into(),
            UnicodeBlock::Rejang => "Rejang".into(),
            UnicodeBlock::HangulJamoExtendedA => "HangulJamoExtendedA".into(),
            UnicodeBlock::Javanese => "Javanese".into(),
            UnicodeBlock::MyanmarExtendedB => "MyanmarExtendedB".into(),
            UnicodeBlock::Cham => "Cham".into(),
            UnicodeBlock::MyanmarExtendedA => "MyanmarExtendedA".into(),
            UnicodeBlock::TaiViet => "TaiViet".into(),
            UnicodeBlock::MeeteiMayekExtensions => "MeeteiMayekExtensions".into(),
            UnicodeBlock::EthiopicExtendedA => "EthiopicExtendedA".into(),
            UnicodeBlock::LatinExtendedE => "LatinExtendedE".into(),
            UnicodeBlock::CherokeeSupplement => "CherokeeSupplement".into(),
            UnicodeBlock::MeeteiMayek => "MeeteiMayek".into(),
            UnicodeBlock::HangulSyllables => "HangulSyllables".into(),
            UnicodeBlock::HangulJamoExtendedB => "HangulJamoExtendedB".into(),
            UnicodeBlock::HighSurrogates => "HighSurrogates".into(),
            UnicodeBlock::HighPrivateUseSurrogates => "HighPrivateUseSurrogates".into(),
            UnicodeBlock::LowSurrogates => "LowSurrogates".into(),
            UnicodeBlock::PrivateUseArea => "PrivateUseArea".into(),
            UnicodeBlock::CJKCompatibilityIdeographs => "CJKCompatibilityIdeographs".into(),
            UnicodeBlock::AlphabeticPresentationForms => "AlphabeticPresentationForms".into(),
            UnicodeBlock::ArabicPresentationFormsA => "ArabicPresentationFormsA".into(),
            UnicodeBlock::VariationSelectors => "VariationSelectors".into(),
            UnicodeBlock::VerticalForms => "VerticalForms".into(),
            UnicodeBlock::CombiningHalfMarks => "CombiningHalfMarks".into(),
            UnicodeBlock::CJKCompatibilityForms => "CJKCompatibilityForms".into(),
            UnicodeBlock::SmallFormVariants => "SmallFormVariants".into(),
            UnicodeBlock::ArabicPresentationFormsB => "ArabicPresentationFormsB".into(),
            UnicodeBlock::HalfwidthandFullwidthForms => "HalfwidthandFullwidthForms".into(),
            UnicodeBlock::Specials => "Specials".into(),
            UnicodeBlock::LinearBSyllabary => "LinearBSyllabary".into(),
            UnicodeBlock::LinearBIdeograms => "LinearBIdeograms".into(),
            UnicodeBlock::AegeanNumbers => "AegeanNumbers".into(),
            UnicodeBlock::AncientGreekNumbers => "AncientGreekNumbers".into(),
            UnicodeBlock::AncientSymbols => "AncientSymbols".into(),
            UnicodeBlock::PhaistosDisc => "PhaistosDisc".into(),
            UnicodeBlock::Lycian => "Lycian".into(),
            UnicodeBlock::Carian => "Carian".into(),
            UnicodeBlock::CopticEpactNumbers => "CopticEpactNumbers".into(),
            UnicodeBlock::OldItalic => "OldItalic".into(),
            UnicodeBlock::Gothic => "Gothic".into(),
            UnicodeBlock::OldPermic => "OldPermic".into(),
            UnicodeBlock::Ugaritic => "Ugaritic".into(),
            UnicodeBlock::OldPersian => "OldPersian".into(),
            UnicodeBlock::Deseret => "Deseret".into(),
            UnicodeBlock::Shavian => "Shavian".into(),
            UnicodeBlock::Osmanya => "Osmanya".into(),
            UnicodeBlock::Osage => "Osage".into(),
            UnicodeBlock::Elbasan => "Elbasan".into(),
            UnicodeBlock::CaucasianAlbanian => "CaucasianAlbanian".into(),
            UnicodeBlock::LinearA => "LinearA".into(),
            UnicodeBlock::CypriotSyllabary => "CypriotSyllabary".into(),
            UnicodeBlock::ImperialAramaic => "ImperialAramaic".into(),
            UnicodeBlock::Palmyrene => "Palmyrene".into(),
            UnicodeBlock::Nabataean => "Nabataean".into(),
            UnicodeBlock::Hatran => "Hatran".into(),
            UnicodeBlock::Phoenician => "Phoenician".into(),
            UnicodeBlock::Lydian => "Lydian".into(),
            UnicodeBlock::MeroiticHieroglyphs => "MeroiticHieroglyphs".into(),
            UnicodeBlock::MeroiticCursive => "MeroiticCursive".into(),
            UnicodeBlock::Kharoshthi => "Kharoshthi".into(),
            UnicodeBlock::OldSouthArabian => "OldSouthArabian".into(),
            UnicodeBlock::OldNorthArabian => "OldNorthArabian".into(),
            UnicodeBlock::Manichaean => "Manichaean".into(),
            UnicodeBlock::Avestan => "Avestan".into(),
            UnicodeBlock::InscriptionalParthian => "InscriptionalParthian".into(),
            UnicodeBlock::InscriptionalPahlavi => "InscriptionalPahlavi".into(),
            UnicodeBlock::PsalterPahlavi => "PsalterPahlavi".into(),
            UnicodeBlock::OldTurkic => "OldTurkic".into(),
            UnicodeBlock::OldHungarian => "OldHungarian".into(),
            UnicodeBlock::RumiNumeralSymbols => "RumiNumeralSymbols".into(),
            UnicodeBlock::Brahmi => "Brahmi".into(),
            UnicodeBlock::Kaithi => "Kaithi".into(),
            UnicodeBlock::SoraSompeng => "SoraSompeng".into(),
            UnicodeBlock::Chakma => "Chakma".into(),
            UnicodeBlock::Mahajani => "Mahajani".into(),
            UnicodeBlock::Sharada => "Sharada".into(),
            UnicodeBlock::SinhalaArchaicNumbers => "SinhalaArchaicNumbers".into(),
            UnicodeBlock::Khojki => "Khojki".into(),
            UnicodeBlock::Multani => "Multani".into(),
            UnicodeBlock::Khudawadi => "Khudawadi".into(),
            UnicodeBlock::Grantha => "Grantha".into(),
            UnicodeBlock::Newa => "Newa".into(),
            UnicodeBlock::Tirhuta => "Tirhuta".into(),
            UnicodeBlock::Siddham => "Siddham".into(),
            UnicodeBlock::Modi => "Modi".into(),
            UnicodeBlock::MongolianSupplement => "MongolianSupplement".into(),
            UnicodeBlock::Takri => "Takri".into(),
            UnicodeBlock::Ahom => "Ahom".into(),
            UnicodeBlock::WarangCiti => "WarangCiti".into(),
            UnicodeBlock::PauCinHau => "PauCinHau".into(),
            UnicodeBlock::Bhaiksuki => "Bhaiksuki".into(),
            UnicodeBlock::Marchen => "Marchen".into(),
            UnicodeBlock::Cuneiform => "Cuneiform".into(),
            UnicodeBlock::CuneiformNumbersandPunctuation => "CuneiformNumbersandPunctuation".into(),
            UnicodeBlock::EarlyDynasticCuneiform => "EarlyDynasticCuneiform".into(),
            UnicodeBlock::EgyptianHieroglyphs => "EgyptianHieroglyphs".into(),
            UnicodeBlock::AnatolianHieroglyphs => "AnatolianHieroglyphs".into(),
            UnicodeBlock::BamumSupplement => "BamumSupplement".into(),
            UnicodeBlock::Mro => "Mro".into(),
            UnicodeBlock::BassaVah => "BassaVah".into(),
            UnicodeBlock::PahawhHmong => "PahawhHmong".into(),
            UnicodeBlock::Miao => "Miao".into(),
            UnicodeBlock::IdeographicSymbolsandPunctuation => {
                "IdeographicSymbolsandPunctuation".into()
            }
            UnicodeBlock::Tangut => "Tangut".into(),
            UnicodeBlock::TangutComponents => "TangutComponents".into(),
            UnicodeBlock::KanaSupplement => "KanaSupplement".into(),
            UnicodeBlock::Duployan => "Duployan".into(),
            UnicodeBlock::ShorthandFormatControls => "ShorthandFormatControls".into(),
            UnicodeBlock::ByzantineMusicalSymbols => "ByzantineMusicalSymbols".into(),
            UnicodeBlock::MusicalSymbols => "MusicalSymbols".into(),
            UnicodeBlock::AncientGreekMusicalNotation => "AncientGreekMusicalNotation".into(),
            UnicodeBlock::TaiXuanJingSymbols => "TaiXuanJingSymbols".into(),
            UnicodeBlock::CountingRodNumerals => "CountingRodNumerals".into(),
            UnicodeBlock::MathematicalAlphanumericSymbols => {
                "MathematicalAlphanumericSymbols".into()
            }
            UnicodeBlock::SuttonSignWriting => "SuttonSignWriting".into(),
            UnicodeBlock::GlagoliticSupplement => "GlagoliticSupplement".into(),
            UnicodeBlock::MendeKikakui => "MendeKikakui".into(),
            UnicodeBlock::Adlam => "Adlam".into(),
            UnicodeBlock::ArabicMathematicalAlphabeticSymbols => {
                "ArabicMathematicalAlphabeticSymbols".into()
            }
            UnicodeBlock::MahjongTiles => "MahjongTiles".into(),
            UnicodeBlock::DominoTiles => "DominoTiles".into(),
            UnicodeBlock::PlayingCards => "PlayingCards".into(),
            UnicodeBlock::EnclosedAlphanumericSupplement => "EnclosedAlphanumericSupplement".into(),
            UnicodeBlock::EnclosedIdeographicSupplement => "EnclosedIdeographicSupplement".into(),
            UnicodeBlock::MiscellaneousSymbolsandPictographs => {
                "MiscellaneousSymbolsandPictographs".into()
            }
            UnicodeBlock::Emoticons => "Emoticons".into(),
            UnicodeBlock::OrnamentalDingbats => "OrnamentalDingbats".into(),
            UnicodeBlock::TransportandMapSymbols => "TransportandMapSymbols".into(),
            UnicodeBlock::AlchemicalSymbols => "AlchemicalSymbols".into(),
            UnicodeBlock::GeometricShapesExtended => "GeometricShapesExtended".into(),
            UnicodeBlock::SupplementalArrowsC => "SupplementalArrowsC".into(),
            UnicodeBlock::SupplementalSymbolsandPictographs => {
                "SupplementalSymbolsandPictographs".into()
            }
            UnicodeBlock::CJKUnifiedIdeographsExtensionB => "CJKUnifiedIdeographsExtensionB".into(),
            UnicodeBlock::CJKUnifiedIdeographsExtensionC => "CJKUnifiedIdeographsExtensionC".into(),
            UnicodeBlock::CJKUnifiedIdeographsExtensionD => "CJKUnifiedIdeographsExtensionD".into(),
            UnicodeBlock::CJKUnifiedIdeographsExtensionE => "CJKUnifiedIdeographsExtensionE".into(),
            UnicodeBlock::CJKCompatibilityIdeographsSupplement => {
                "CJKCompatibilityIdeographsSupplement".into()
            }
            UnicodeBlock::Tags => "Tags".into(),
            UnicodeBlock::VariationSelectorsSupplement => "VariationSelectorsSupplement".into(),
            UnicodeBlock::SupplementaryPrivateUseAreaA => "SupplementaryPrivateUseAreaA".into(),
            UnicodeBlock::SupplementaryPrivateUseAreaB => "SupplementaryPrivateUseAreaB".into(),
        },
        None => "Unknown Unicode Block".into(),
    }
}
